### PR TITLE
adaptation to joomla_4.0 and joomla_5.0

### PR DESCRIPTION
**Pull request by JLTRY**
I adapted component_attachments and 3 of the plugins for joomla 4.0 and now joomla_5.0

### CODE REVIEW

**Comment by Kimball31** [comment]
Theofilos Intzoglou also working on a modified version for Joomal 4. 
https://github.com/DSE-Western-Thessaloniki/attachments

**Comment by TinoJ** [comment]
> I adapted component_attachments and 3 of the plugins for joomla 4.0 and now joomla_5.0

@JLTRY  Ui, I am surprised and happy that I had a look into the issues. I am preparing my website currently for the J4 update and run into the "unsupported problem" with Attachments. I did not find any replacement extension yet. :-(

Should I wait on your result before I give up on Attachments or could I test something to support you? (I am not a developer).

**Comment by JLTRY** [comment]
> > I adapted component_attachments and 3 of the plugins for joomla 4.0 and now joomla_5.0
> 
> @JLTRY Ui, I am surprised and happy that I had a look into the issues. I am preparing my website currently for the J4 update and run into the "unsupported problem" with Attachments. I did not find any replacement extension yet. :-(
> 
> Should I wait on your result before I give up on Attachments or could I test something to support you? (I am not a developer).

Hello the modification are there but no packaging to setup directly in Joomla . If you want to update your site you need to access to it through ftp and have rights to copy files there. Let me know I will give you the instructions. If you have no access you need to wait until I prepare a new release package

**Comment by Kimball31** [comment]
> Hello the modification are there but no packaging to setup directly in Joomla . If you want to update your site you need to access to it through ftp and have rights to copy files there. Let me know I will give you the instructions. If you have no access you need to wait until I prepare a new release package

@JLTRY,
What about downloading the project (https://github.com/JLTRY/attachments/tree/master) and running Make? 
Then use the Joomla install Upload Package File option to install the package? 
Would that work?

**Comment by TinoJ** [comment]
> Hello the modification are there but no packaging to setup directly in Joomla . If you want to update your site you need to access to it through ftp and have rights to copy files there. Let me know I will give you the instructions. If you have no access you need to wait until I prepare a new release package

Hello, I have full access locally and remote via sftp. It would be nice to have instructions on what to download and upload and what to keep in mind when updating. (I am not (yet) familiar with Make.)

**Comment by JLTRY** [comment]
> > Hello the modification are there but no packaging to setup directly in Joomla . If you want to update your site you need to access to it through ftp and have rights to copy files there. Let me know I will give you the instructions. If you have no access you need to wait until I prepare a new release package
> 
> @JLTRY Hello, I have full access locally and remote via sftp. It would be nice to have instructions on what to download and upload and what to keep in mind when updating. (I am not (yet) familiar with Make.)

Hello if your component is alredy installed in a previous version of joomla 
you need only to copy the modified directories through ftp
download locally my repo
Then transfer directories
F:\Sites\repos\attachments\attachments_component\admin => administrator/components/com_attachments
F:\Sites\repos\attachments\attachments_component\site  => components/com_attachments
F:\Sites\repos\attachments\attachments_for_content => plugins/attachments/attachments_for_content
F:\Sites\repos\attachments\attachments_plugin_framework => plugins/attachments/attachments_plugin_framework
F:\Sites\repos\attachments\attachments_for_content => plugins/content/attachments

For first install I did not make a packaging

**Comment by TinoJ** [comment]
Hi,
thank you very much.
Should the last line be F:\Sites\repos\attachments\attachments_plugin => plugins/content/attachments ?

I think something is missing or I made a mistake. I cannot systematically test, because I do not know, what function is included in each folder. My system is still on 3.10.x, if this is the problem.

I get "Call to undefined method Joomla\CMS\Application\AdministratorApplication::getInput()"
opening Admin > Components > Attachments
I get "Call to undefined method Joomla\CMS\Application\AdministratorApplication::getDispatcher()"
opening Admin > Content > Articles
opening Admin > Content > Category
opening Admin > Content > Featured Articles
I get "Call to undefined method Joomla\CMS\Application\AdministratorApplication::getInput() "
opening Admin > Global Configuration > Component Attachments

Any idea, what I should check? :)

**Comment by JLTRY** [comment]
> Hi, thank you very much. Should the last line be F:\Sites\repos\attachments\attachments_plugin => plugins/content/attachments ?
> 
> I think something is missing or I made a mistake. I cannot systematically test, because I do not know, what function is included in each folder. My system is still on 3.10.x, if this is the problem.
> 
> I get "Call to undefined method Joomla\CMS\Application\AdministratorApplication::getInput()" opening Admin > Components > Attachments I get "Call to undefined method Joomla\CMS\Application\AdministratorApplication::getDispatcher()" opening Admin > Content > Articles opening Admin > Content > Category opening Admin > Content > Featured Articles I get "Call to undefined method Joomla\CMS\Application\AdministratorApplication::getInput() " opening Admin > Global Configuration > Component Attachments
> 
> Any idea, what I should check? :)

yes for last line
Sorry but I did not adapt the code to be compatible with Joomla 3.0 that is very old . You need to install first at least joomla 4.0
Disable if needed the components/plugins attachments; you can do it in your database (mysql request)
UPDATE `jom30_extensions` SET `enabled` = '0' WHERE `jom30_extensions`.`name` like '%attach%';

**Comment by TinoJ** [comment]
Thanks, I did the migration with all disabled, and afterwards I enabled all attachement extension parts again.
Unfortunately then the backend is "broken" with error message "Class "JRequest" not found".
The error pops-up when I click on System or Content and so on.

I will keep the attachment package disabled for the moment. I had to discover, that my site template is not compatible with J4.x, and now I need to adapt a new template. :(

grafik
grafik

**Comment by yozmag** [comment]
Hello have work on this some time ago, but had to stop. I used the 3.10 version and removed all depreciated , including Jrequest, I followed the  coding of joomla [weblink,](https://github.com/joomla-extensions/weblinks). Joomla sad that an running version of 3.10 without deprecated should run on 4.0. Maybe if you look at my changes, [attachments_component.tar.gz](https://github.com/jmcameron/attachments/files/13751538/attachments_component.tar.gz) you can see how to replace jrequest. You can download . I haven't update my repo with these changes, because of my lack of git knowledge, but I have a local git repo on my machine.

**Comment by JLTRY** [comment]
> Theofilos Intzoglou also working on a modified version for Joomal 4. https://github.com/DSE-Western-Thessaloniki/attachments

You are right Thoefolos implementaion is better wit respect of new file structure for Joomla 4.0 components

**Comment by parapente** [comment]
@JLTRY as Cameron doesn't have the time to continue supporting the extension for new versions of Joomla I have created a new mirror repository in https://github.com/DSE-Western-Thessaloniki/attachments_next to work on testing and releasing a new version of the extension for Joomla4.x+. 

There are no packages in releases as I need to at least change the name and the release version for every plugin/component and find a way to automate testing of the code. If anyone wants to test the extension and has the make command installed in his system, running make in the root directory of the project, the system will create the package (although I would advise installing the framework and plugins before the component). You can find the separate zip files in the pkg_attachments/packages folder.

The extension should work on Joomla4 and I'm working on supporting Joomla5 too. Feel free to contribute if you want.

**Comment by jmcameron** [comment]
@JLTRY and @parapente, please email me and let discuss how to move forward.

**Comment by JLTRY** [comment]
> @JLTRY and @parapente, please email me and let discuss how to move forward.

Hello, I agree with @parapente to continue the work with a new repository dedicated to version 4 and higher
Let us know if you prefer to keep your repo and have the time to merge the modifications for version 4 version of @parapente is working fine

**Comment by JLTRY** [comment]
Jonathan invited me to collaborate. So that I will close this pull request

**Comment by JLTRY** [comment]
@jmcameron do you agree to create a dedicated branch for version 3.0 and continue in master for version 4.x and 5.x ?

**Comment by jmcameron** [comment]
> @jmcameron do you agree to create a dedicated branch for version 3.0 and continue in master for version 4.x and 5.x ?

Yes, go ahead. That seems smart so that we can retain a working version for Joomla 3.0 while moving forward on 'master' current versions.

**Comment by JLTRY** [comment]
pull request closed as version from @parapente is better

**Pull request closed without merging**
