### PR TITLE
Version 4.0.2

### PR DESCRIPTION
**Pull request by JLTRY**
@parapente  
setversions to 4.0.2
add parameter for automatic update
You can test it with https://github.com/JLTRY/attachments/releases/download/v4.0.1/attachments-4.0.1.zip
(I have updated the package manifest file to point to an update xml file
<server type="extension" priority="1" name="Attachments Updates">https://raw.githubusercontent.com/JLTRY/attachments/master/pkg_attachments/update_pkg.xml</server>
https://github.com/jmcameron/attachments/compare/master...JLTRY:attachments:V4.0.1 )
that updates automatically to version v4.0.2

### CODE REVIEW

**Comment by JLTRY** [comment]
Once you have tested  I will change url to point to main repo

**Comment by parapente** [comment]
Nice idea! I tested it and it seems to work just fine. I installed the 4.0.1 version and joomla detected there was a new version 4.0.2 which was then used to update the extension. Can we use the releases from this repository though? I don't mind checking your github account for the xml but I think we should have one common repository for the packaged zip files

**Comment by JLTRY** [comment]
OK let change the url and merge it . I will also update the tarball for version v4.0.1 and create the one for v4.0.2

**Comment by JLTRY** [comment]
I updated the v4.0.1 tarball and created the new v4.0.2 release

**Comment by parapente** [comment]
Super!

**Comment by JLTRY** [comment]
@jmcameron we have provided a way to automatically update the version 4+ with an url to the update xml on github and inside update the last release provided
Could you please add a reference to this link [attachments/releases](https://github.com/jmcameron/attachments/releases/)
inside [joomla extensions attachement page](https://extensions.joomla.org/extension/directory-a-documentation/downloads/attachments/) page, so that the extension can be more popular ? Thank you

**Comment by jmcameron** [comment]
> @jmcameron we have provided a way to automatically update the version 4+ with an url to the update xml on github and inside update the last release provided Could you please add a reference to this link [attachments/releases](https://github.com/jmcameron/attachments/releases/) inside [joomla extensions attachement page](https://extensions.joomla.org/extension/directory-a-documentation/downloads/attachments/) page, so that the extension can be more popular ? Thank you

@JLTRY I've updated the listing.  If you want any of the extension description changed, please send me an edited version of the description to my personal email.   Thanks!

**Pull request merged**
