### PR TITLE
Fix #79 add translation for turkish

### LINKED ISSUE #79: Issues For Attachments v4.0.3
Hello,

Two issues for the Attachments v4.0.3 component. Please see the images.

image-1
image-2

### PR DESCRIPTION
**Pull request by JLTRY**
add zip file 
[tr-TR-For-attachments-4.0.4.zip](https://github.com/user-attachments/files/17698636/tr-TR-For-attachments-4.0.4.zip)
Turkish Translator&Math Teacher - Mehmet Taş

### CODE REVIEW

**Comment by parapente** [comment]
I believe we should keep the various languages in language packs as it was before. Leaving them in the main repository may result in partial translations for languages between releases. Language packs will have the same version as the main release if they don't have any string changes. Otherwise will remain in the previous version until updated. I'll work on transfering the greek language files in the language packs repo too.

**Comment by mckillo** [comment]
I agree. In my opinion, the master should only include en-GB, and the rest of the languages should be in separate packs. For example, if I want to add the spanish pack, this translation must not include in the main version (only on-demand by language pack, other zip file). Each admin will use one or more languages on the website with Joomla (not all).

**Comment by JLTRY** [comment]
@parapente @mckillo  I agree I will create a separate turkish language pack based on the zip file
@parapente let me know if we can keep English french and Greek in attachments , as we maintain both repo and it could be easier for us to adapt both code and language

**Comment by parapente** [comment]
Sure @JLTRY  if you want we may keep those two languages in main.

**Comment by JLTRY** [comment]
the modifcations are done under https://github.com/jmcameron/attachments_translations/pull/4

**Pull request closed without merging**
