### PR TITLE
New features introduced: hide empty brackets, alternative search result

### PR DESCRIPTION
**Pull request by yild**
This fork introduce:
1. Option to hide 'unnecessary' bracket chars [] when 'description' field and user defined fields are empty,
2. Clickable search result titles that links to content to which attachment was attached, rather than to file/url itself, both article and/or category.

Both options are added to config.xml, default off.

ps. if i did everything correct this should work out of the box - i'm new to this github thing ;)

### CODE REVIEW

**Comment by yild** [comment]
bump

**Comment by yild** [comment]
bump @jmcameron

**Comment by parapente** [comment]
@yild I am interested in adding the configuration option for hiding the empty brackets but I don't think it is worth it to add new code/options for the attachments_search plugin. This plugin depends on com_search which is now deprecated and com_finder should be used instead. Do you have the time to update the code so it merges with master with the necessary changes?

**Comment by JLTRY** [comment]
The implementation for adavanced search was done for Joomla 3.0
The idea was to add a link to the article or the category associated with the attachment
Before modification
joomla 3 search
After modification

joomla 3 search new

**Comment by parapente** [comment]
Closing as PR #96 was merged with the code for hiding the empty brackets. Thank you @yild

**Pull request closed without merging**
