### PR TITLE
Correct add attachment in backend

### PR DESCRIPTION
**Pull request by JLTRY**
@parapente 
correct ReferenceError: submitbutton is not defined
in add Attachment for article in backend

### CODE REVIEW

**Comment by parapente** [comment]
@JLTRY applying this patch doesn't seem to solve the issue here. Actually submitbutton function is supposed to be used for client side form validation but it isn't set up correctly now. The right way for Joomla 4 & 5 is described [here](http://pr-240.manual.joomlacode.org/docs/general-concepts/forms/client-side-validation).

Specifically we need to add in default.php:86:
```php
Factory::getApplication()->getDocument()->getWebAssetManager()->useScript('form.validate');
```

and then replace the input button with a normal button in line 225:
```diff
-	   <input type="submit" name="Submit" class="button"
-			  value="<?php echo Text::_('ATTACH_UPLOAD_VERB'); ?>" />
+        <button type="button" class="btn btn-primary" onclick="Joomla.submitbutton('attachment.saveNew')"><?php echo Text::_('ATTACH_UPLOAD_VERB'); ?></button>
```

However there is more work to be done in the attachments.xml

**Comment by JLTRY** [comment]
@parapente modifications done
let me know what to do for file attachments.xml

**Comment by parapente** [comment]
In line 97:
```diff
- <form class="attachmentsBackend" enctype="multipart/form-data"
+ <form class="attachmentsBackend form-validate" enctype="multipart/form-data"
```

Also a small visual fix in line 236:
```diff
- 		  <input type="button" name="cancel" value="<?php echo Text::_('ATTACH_CANCEL'); ?>"
+		  <input class="btn btn-primary" type="button" name="cancel" value="<?php echo Text::_('ATTACH_CANCEL'); ?>"
```

attachment.xml doesn't seem to require further changes for now but it would be nice to make the same changes to every other templates that create a similar form.

**Comment by JLTRY** [comment]
@parapente  hello I corrected with your remarks

**Comment by parapente** [comment]
@JLTRY sorry I didn't have a lot of free time lately to look it any further. Feel free to merge if it doesn't break anything. We might have to adapt the rest of the forms later too.

**Pull request merged**
