### PR TITLE
correction for  Blank page in popup after adding file #41 

### PR DESCRIPTION
**Pull request by JLTRY**
correction for  Blank page in popup after adding file #41 
+ correct version 4.0.0

### CODE REVIEW

**Comment by JLTRY** [comment]
@parapente   do you agree to merge.
I corrected the blank page issue
I changed also some version to 4.0.1
If merged I will provide a relase 4.0.1

**Comment by parapente** [comment]
@JLTRY When applying the patch the situation seems to be worse than before. In the frontend, without the patch, when you are editing an article, the attachment list is updated correctly when adding a new file. Using the patch, the attachment list isn't updated without reloading the page. I think it needs some more work to fix it correctly but you are on the right track.

As it is without your changes the only thing that doesn't work correctly is when you don't edit the article and try to just add a new attachment. For some reason after uploading the file the form isn't reloaded and remains blank. Also please see the comments I added above to the code. I will try to have a look at it tomorrow morning.

**Comment by JLTRY** [comment]
@parapente you are right the attachment list is no more updated. I will check again the correction. To be noticed that this issue was present since the beginning !!! For instance on my joomla 3.x site it is also present . The blank page is due to the exit() line in file attachments_component\site\src\Controller\DisplayController.php, function save() . The main idea of the correction is to redirect to the initial upload url , and move the refresh part in the template of Upload. For an unknown reason it woked on my local tests and not on the final commit when I removed my traces. I will check again.

**Comment by JLTRY** [comment]
@parapente your correction is better

**Pull request closed without merging**
